config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'about' => 'homes#about'
  devise_for :users
  resources :users, only:[:index, :show, :edit, :update]do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :magazines do
      resources :comments, only:[:create, :destroy]
      resource :favorites, only: [:create, :destroy]
  end
  get 'searches/search' => 'searches/search', as: "search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :magazine
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :magazine
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def self.search_for(content, method)
    if method == 'perfect'
      Magazine.where(title: content)
    elsif method == 'forward'
      Magazine.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Magazine.where('title LIKE ?', '%'+content)
    else
      Magazine.where('title LIKE ?', '%'+content+'%')
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile
  has_many :magazines
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
    # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
    
  def get_profile(width, height)
    unless profile.attached?
      file_path = Rails.root.join('app/assets/images4/essiii.jpg')
      profile.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
   user_path(@user.id)
  end
  
  def after_sign_out_path_for(resource)
  root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @magazines = Magazine.find_by(id: params[:magazine_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.magazine_id = @magazines.id
    @comment.save
  end
  
  def destroy
    @magazines = Magazine.find_by(id: params[:magazine_id])
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:comment)
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @magazines = Magazine.find_by(id: params[:magazine_id])
    @favorite = Favorite.new(magazine_id: @magazines.id)
    @favorite.user_id = current_user.id
    @favorite.save

  end

  def destroy
    @magazines = Magazine.find_by(id: params[:magazine_id])
    @favorite = Favorite.find_by(magazine_id: @magazines.id)
    @favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  def index
    @magazines = Magazine.all
    @magazine = Magazine.new
  end

  def show
    @magazines = Magazine.find_by(id: params[:id])
    @magazine = Magazine.new
    @user = @magazines.user
    @comment = Comment.new
  end

  def create
    @magazine = Magazine.new(magazine_params)
    @magazine.user_id = current_user.id
    @magazine.save
    redirect_to magazines_path
  end

  def edit
    @magazine = Magazine.find_by(id: params[:id])
  end

  def update
    @magazine = Magazine.find_by(id: params[:id])
    @magazine.update(magazine_params)
    redirect_to magazine_path(@magazine)
  end

  def destroy
    @magazine = Magazine.find_by(id: params[:id])
    @magazine.destroy
    redirect_to magazines_path
  end

  private

  def magazine_params
    params.require(:magazine).permit(:title, :body)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search

    def search
      @model=params[:model]
      @content=params[:content]
      @method=params[:method]
      if @model == 'user'
        @records=User.search_for(@content,@method)
      else
        @records=Magazine.search_for(@content,@method)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find_by(id: params[:id])
    @users = User.all
    @magazine = Magazine.new
  end

  def show
    @user = User.find_by(id: params[:id])
    @magazine = Magazine.new
    @magazines = @user.magazines
  end

  def edit
    @user = User.find_by(id: params[:id])
  end
  def update
    @user = User.find_by(id: params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<table>
  <% magazines.comments.each do |comment| %>
    <tr>
      <td>
        <%= link_to magazine_path(magazines) do %>
         <%= image_tag comment.user.get_profile(50, 50) %>
         <% end %>
      </td>
      <td>
        <%= comment.comment %>
      </td>
      <td><%= link_to "削除", magazine_comment_path(comment.magazine,comment), method: :delete, remote: true %></td>
    </tr>
  <% end %>
</table>

app/views/comments/create.js.erb
$('#comments_<%= @magazines.id %>').html('<%= j(render "comments/comments", magazines: @magazines) %>');

app/views/comments/destroy.js.erb
$('#comments_<%= @magazines.id %>').html('<%= j(render "comments/comments", magazines: @magazines) %>');

app/views/favorites/_favorite.html.erb
<% if magazines.favorited_by?(current_user) %>
   <%= link_to magazine_favorites_path(magazines), method: :delete, remote: true do %>
    <%= magazines.favorites.count %> ♥️
   <% end %>
<% else %>
   <%= link_to magazine_favorites_path(magazines), method: :post, remote: true do %>
    <%= magazines.favorites.count %> ♡️
   <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @magazines.id %>').html('<%= j(render "favorites/favorite", magazines: @magazines) %>');

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @magazines.id %>').html('<%= j(render "favorites/favorite", magazines: @magazines) %>');

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/magazines/_magazines.html.erb
<h2>BOOKS</h2>
<table class="table">
  <tr>
    <th></th>
    <th>
      <h4>title</h4>
    </th>
    <th>
      <h4>body</h4>
    </th>
  </tr>
       <% magazines.each do |magazine| %>
          <tr>
            <td>
              <%= link_to magazine_path(magazine) do %>
               <%= image_tag magazine.user.get_profile(100, 100) %>
               <% end %>
            </td>
            <td>
              <%= link_to magazine.title, magazine_path(magazine) %> 
            </td>
                 
            <td><%= magazine.body %></td>
          </tr>
        <% end %>
 </table>

app/views/magazines/_make.html.erb
<h3 class="mt-5">NEW BOOK</h3> 
<%= form_with model: magazine ,url: magazines_path, method: :post do |f|%>
 <div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title ,class: "form-control book_title" %>
 </div>
 <div class="form-group">
  <%= f.label :body %>
  <%= f.text_area :body, class: "form-control book_body"%>
 </div>
 <div class="form-group">
  <%= f.submit "Create Book", class: "btn btn-outline-dark"%>
 </div>
<% end %>

app/views/magazines/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-5 mx-auto">
     <h3>Editing Magazine</h3>
       <%= form_with model: @magazine do |f|%>
       <div class="form-group mt-4">
          <p>NAME</p>
          <%= f.text_field :title ,class: "form-control book_title" %>
       </div>  
        <div class="form-group mt-4">
          <p>INTRODUCTION</p>
          <%= f.text_area :body ,class: "form-control book_title" %>
        </div>
        <div class="form-group mt-4">
          <p>PROFILE</p>
          <%= f.file_field :profile, placeholder:"profile", accept: "image/*" , class: "btn btn-outline-secondary" %>
        </div>
        <%= f.submit "Update Book", class: "btn btn-outline-dark" %>
        <% end %>
    </div>
  </div>
</div>

app/views/magazines/index.html.erb
<div class="container mt-5">
  <div class="row d-flex justify-content-between">
    <div class="col-md-3">
      <%= render "users/user", user: current_user %>
      <%= render "make", magazine: @magazine %>
    </div>

    <div class="col-8 ml-5">
     <%= render "magazines", magazines: @magazines %>
    </div>
  </div>

</div>

app/views/magazines/new.html.erb
<h1>Magazines#new</h1>
<p>Find me in app/views/magazines/new.html.erb</p>

app/views/magazines/show.html.erb
<div class="container mt-5">
  <div class="row d-flex justify-content-between">
    <div class="col-md-3">
      <%= render "users/user", user: @user %>
      <%= render "make", magazine: @magazine %>
    </div>

   <div class="col-8 ml-5">
     <h3>DETAILE</h3>
       <table class="table">
        <tr>
          <td class="col-1"><%= image_tag @magazines.user.get_profile(100, 100) %></td>
          <td><%= link_to @magazines.title, magazine_path(@magazines)  %></td>
          <td><%= @magazines.body %></td>
          <% if @magazines.user == current_user %>
           <td><%= link_to "Edit", edit_magazine_path(@magazines) ,class: "btn btn-outline-secondary" %></td>
           <td><%= link_to "Destroy", magazine_path(@magazines), method: :delete ,class: "btn btn-inline-secondary"%></td>
          <% end %>
          <td id="favorite_buttons_<%= @magazines.id %>">
             <%= render "favorites/favorite", magazines: @magazines %>
          </td>
          <td><%= @magazines.comments.count %>コメント</td>
        </tr>
     </table>
        <div>
            <div id="comments_<%= @magazines.id %>">
               <%= render "comments/comments", magazines: @magazines %>
            </div>
        </div>
        <div>
        <h3 class="mt-5">NEW BOOK</h3>
          <%= form_with model: [@magazines,@comment], local: false do |f|%>
           <div class="form-group">
            <%= f.label :comment %>
            <%= f.text_area :comment ,class: "form-control book_title" %>
           </div>
           <div class="form-group">
            <%= f.submit "Comment", class: "btn btn-outline-dark"%>
           </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/relationships/_follow.html.erb
<% if users.exists? %>
  <% users.each do |user| %>
    <table>
      <thead>
        <tr>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= image_tag user.get_profile(50, 50) %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followers.html.erb
<%= render "follow", users: @users %>

app/views/relationships/followings.html.erb
<%= render "follow", users: @users %>

app/views/searches/search.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @model == "user" %>
    <h2>Users search for '<%= @content %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Introduction</th>
            </tr>
        </thead>
    <% @records.each do |user| %>
        <tbody>
            <tr>
                <th>
                    <%= image_tag user.get_profile(50, 50) %>
                </th>
                <th>
                    <%= user.name %>
                </th>
                <th>
                    <%= user.introduction %>
                </th>
            </tr>
        </tbody>
    <% end %>
    <% elsif @model == "magazine" %>
    <h2>Books search for '<%= @content %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
            </tr>
        </thead>
        <% @records.each do |magazine| %>
        <tbody>
            <tr>
                <th>
                    <%= attachment_image_tag(magazine.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                    <%= magazine.title %>
                </th>
                <th>
                    <%= magazine.body %>
                </th>
            </tr>
        </tbody>
        <% end %>
    <% end %>
    </table>
  </div>
</div>

app/views/users/_user.html.erb
<h3>USER INFO</h3>
<%= image_tag user.get_profile(100, 100) %>
  <table class="table">
    <tr></tr>
    <tr>
      <th>NAME</th>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <th>INTRODUCTION</th>
      <td><%= user.introduction %></td>
    </tr>
  </table>
  <%= link_to  "EDIT",edit_user_path(current_user.id) , class: "btn btn-outline-secondary w-100" %>

app/views/users/edit.html.erb
<h3>editer</h3>

<%= form_with model: @user, url: user_path, method: :patch do |f| %>
 <p>name</p>
 <%= f.text_field :name, placeholder:"name" %>
 <p>introduction</p>
 <%= f.text_area :introduction, placeholder:"introduction" %>
 <p>profile</p>
 <%= f.file_field :profile, placeholder:"profile", accept: "image/*" %>
 <%= f.submit "end"%>
<% end %>

app/views/users/index.html.erb
<div class="container mt-5">
  <div class="row d-flex justify-content-between">
    <div class="col-md-3">
      <%= render "user", user: current_user %>
      <%= render "magazines/make", magazine: @magazine %>
    </div>

    <div class="col-8 ml-5">
     <table class="table">
       <h2>USERS</h2>
    <thead>
      <tr>
        <th>image</th>
        <th>
          <h4>Name</h4>
        </th>
        <th colspan="3"></th>
       </tr>
     </thead>
           <% @users.each do |user| %>
           <tbody>
              <tr>
                <td><%= link_to user_path(user) do %>
                     <%= image_tag user.get_profile(100, 100) %>
                    <% end %>
                </td>
                <th><h5 class="mt-3"><%= user.name%></h5></th>
                <td>
                  <%= link_to "show", user_path(user) ,class: "btn btn-outline-info btn-sm mt-3"%>
                </td>
                <td>
                  <% if current_user.following?(user) %>
                    <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                  <% end %>
                </td>
              </tr>
          </tbody>
            <% end %>
     </table>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row d-flex justify-content-between">
    <div class="col-3">
      <%= render "user", user: @user %>
      <%= link_to "follow", user_followings_path(@user) %>
      <%= link_to "follower", user_followers_path(@user) %>
      <%= render "magazines/make", magazine: @magazine %>
    </div>

    <div class="col-8 ml-5">
     <%= render "magazines/magazines", magazines: @magazines %>
    </div>
  </div>
</div>