config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'about' => 'homes#about'
  devise_for :users
  resources :users, only:[:index, :show, :edit, :update]do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :magazines do
      resources :comments, only:[:create, :destroy]
      resource :favorites, only: [:create, :destroy]
  end
  get 'searches/search' => 'searches/search', as: "search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :magazine
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :magazine
end

app/models/magazine.rb
class Magazine < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def self.search_for(content, method)
    if method == 'perfect'
      Magazine.where(title: content)
    elsif method == 'forward'
      Magazine.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Magazine.where('title LIKE ?', '%'+content)
    else
      Magazine.where('title LIKE ?', '%'+content+'%')
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile
  has_many :magazines
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
    # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
    
  def get_profile(width, height)
    unless profile.attached?
      file_path = Rails.root.join('app/assets/images4/essiii.jpg')
      profile.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @magazines = Magazine.find_by(id: params[:magazine_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.magazine_id = @magazines.id
    @comment.save
  end
  
  def destroy
    @magazines = Magazine.find_by(id: params[:magazine_id])
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:comment)
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @magazines = Magazine.find_by(id: params[:magazine_id])
    @favorite = Favorite.new(magazine_id: @magazines.id)
    @favorite.user_id = current_user.id
    @favorite.save

  end

  def destroy
    @magazines = Magazine.find_by(id: params[:magazine_id])
    @favorite = Favorite.find_by(magazine_id: @magazines.id)
    @favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  def index
    @magazines = Magazine.all
    @magazine = Magazine.new
  end

  def show
    @magazines = Magazine.find_by(id: params[:id])
    @magazine = Magazine.new
    @user = @magazines.user
    @comment = Comment.new
  end

  def create
    @magazine = Magazine.new(magazine_params)
    @magazine.user_id = current_user.id
    @magazine.save
    redirect_to magazines_path
  end

  def edit
    @magazine = Magazine.find_by(id: params[:id])
  end

  def update
    @magazine = Magazine.find_by(id: params[:id])
    @magazine.update(magazine_params)
    redirect_to magazine_path(@magazine)
  end

  def destroy
    @magazine = Magazine.find_by(id: params[:id])
    @magazine.destroy
    redirect_to magazines_path
  end

  private

  def magazine_params
    params.require(:magazine).permit(:title, :body)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search

    def search
      @model=params[:model]
      @content=params[:content]
      @method=params[:method]
      if @model == 'user'
        @records=User.search_for(@content,@method)
      else
        @records=Magazine.search_for(@content,@method)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find_by(id: params[:id])
    @users = User.all
    @magazine = Magazine.new
  end

  def show
    @user = User.find_by(id: params[:id])
    @magazine = Magazine.new
    @magazines = @user.magazines
  end

  def edit
    @user = User.find_by(id: params[:id])
  end
  def update
    @user = User.find_by(id: params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_search.html.erb
<div class="serch_form">
    <%= form_with url: search_path,method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model,options_for_select({"User"=>"user","Magazine"=>"magazine"})%>
    <%= f.select :method,options_for_select({"完全一致"=>"perfect","前方一致"=>"forward",
        "後方一致"=>"backward","部分一致"=>"partial"})%>
    <%= f.submit'検索' %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container"> 
         <li class="navbar-brand">
           <%= link_to "Bookers", root_path ,class: "navbar-brand"%>
         </li>
        <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-link text-light">
            <%= link_to "HOME", user_path(current_user.id) ,class: "navbar-brand"%>
          </li>
          <li class="nav-link text-light">
            <%= link_to "USER", users_path ,class: "navbar-brand"%>
          </li>
          <li class="nav-link text-light">
            <%= link_to "BOOKS", magazines_path,class: "navbar-brand" %>
          </li>
          <li class="nav-link text-light">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete ,class: "navbar-brand "%>
          </li>
        </ul>
         <% else %>
        <ul class="navbar-nav ">
          <li class="nav-link text-light">
            <%= link_to "home", root_path ,class: "navbar-brand"%>
          </li>
          <li class="nav-link text-light">
            <%= link_to "about", about_path ,class: "navbar-brand"%>
          </li>
          <li class="nav-link text-light">
            <%= link_to "sign up", new_user_registration_path ,class: "navbar-brand"%>
          </li>
          <li class="nav-link text-light">
            <%= link_to "sign in", new_user_session_path ,class: "navbar-brand"%>
          </li>
        </ul>
      </div>
     </div>  
      <% end %>
     </nav>
     <div class="col-5 mx-auto">
        <% if user_signed_in? %>
              <%= render 'layouts/search' %>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>